### ISSUE TITLE
Installing as locally editable package fails

### ISSUE THREAD

**Issue by eharris** [MisterWil/abodepy#21]
When trying to install a local editable version (checked out directly from github):

```
pip install -e abodepy/
```

It fails with the following error:

```
Obtaining file:///[obscured]/abodepy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "[obscured]/abodepy/setup.py", line 4, in <module>
        from abodepy.helpers.constants import (__version__, PROJECT_PACKAGE_NAME,
      File "abodepy/__init__.py", line 29, in <module>
        from abodepy.automation import AbodeAutomation
      File "abodepy/automation.py", line 6, in <module>
        import abodepy.helpers.constants as CONST
      File "abodepy/helpers/constants.py", line 202
    SyntaxError: Non-ASCII character '\xc2' in file abodepy/helpers/constants.py on line 202, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in [obscured]/abodepy/
```

**Comment by MisterWil** [comment]
This must never have worked... but I added some additional README instructions to address this. Should just run `pip install -r requirements.txt -r requirements_test.txt` and that should allow you to install as locally editable.
